"""Schema versioning for the SQLite stores.

Every CodeCortex database is a *derived cache* — nodes, edges, symbols,
occurrences and clusters can all be regenerated by re-indexing the source tree.
So the correct response to a schema change is to rebuild, not to hand-write a
migration: a full migration framework would be more machinery than the data is
worth, and would still lose nothing on failure.

The stamp lives in SQLite's own `PRAGMA user_version`, so it costs no table and
is readable by any client:

    version == 0            fresh database, stamp it
    version == expected     open normally
    version <  expected     stale cache — rebuild (drop + recreate) and stamp
    version >  expected     written by a newer CodeCortex — refuse to touch it

Refusing the last case matters: an older installation silently reinterpreting a
newer schema is how caches get corrupted.
"""

from __future__ import annotations

import logging
import sqlite3

logger = logging.getLogger(__name__)


class SchemaVersionError(RuntimeError):
    """Database was written by a newer CodeCortex than the one reading it."""


def read_schema_version(conn: sqlite3.Connection) -> int:
    return int(conn.execute("PRAGMA user_version").fetchone()[0])


def write_schema_version(conn: sqlite3.Connection, version: int) -> None:
    # PRAGMA does not accept bound parameters; version is an int we control.
    conn.execute(f"PRAGMA user_version = {int(version)}")
    conn.commit()


def ensure_schema(
    conn: sqlite3.Connection,
    *,
    store: str,
    expected: int,
    create_sql: str,
    tables: tuple[str, ...],
    allow_rebuild: bool = True,
) -> str:
    """Bring `conn` to schema version `expected`; return what was done.

    Returns one of "created", "current", "rebuilt". Raises SchemaVersionError if
    the database is newer than this code understands.
    """
    found = read_schema_version(conn)

    if found > expected:
        raise SchemaVersionError(
            f"{store} database is at schema version {found}, but this CodeCortex "
            f"understands up to {expected}. Upgrade CodeCortex or delete the cache."
        )

    if found == expected:
        conn.executescript(create_sql)
        conn.commit()
        return "current"

    is_empty = not _has_any_table(conn, tables)
    if found == 0 and is_empty:
        conn.executescript(create_sql)
        write_schema_version(conn, expected)
        return "created"

    if not allow_rebuild:
        raise SchemaVersionError(
            f"{store} database is at schema version {found}, expected {expected}, "
            f"and rebuilding is disabled."
        )

    logger.info(
        "Rebuilding %s cache: schema version %d → %d (data is regenerated by re-indexing)",
        store,
        found,
        expected,
    )
    for table in reversed(tables):
        conn.execute(f"DROP TABLE IF EXISTS {table}")
    conn.commit()
    conn.executescript(create_sql)
    write_schema_version(conn, expected)
    return "rebuilt"


def _has_any_table(conn: sqlite3.Connection, tables: tuple[str, ...]) -> bool:
    rows = conn.execute("SELECT name FROM sqlite_master WHERE type='table'").fetchall()
    existing = {row[0] for row in rows}
    return any(table in existing for table in tables)
