"""Index-cache migrations.

CodeCortex persists four SQLite stores, and all four are derived from the source
tree — re-indexing reproduces them exactly. So a "migration" here means: detect
a stale schema and rebuild that cache. There is deliberately no Alembic-style
revision chain; there is no user-authored data to preserve, and inventing one
would add a second migration system for caches that can be thrown away.

What this module guarantees is that a schema change is *detected and logged*
rather than silently misread — see `core.db_schema` for the stamping itself.
"""

from __future__ import annotations

import logging
import sqlite3
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Iterable, Optional

from core.db_schema import read_schema_version

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class StoreSpec:
    """How to recognise and reopen one CodeCortex SQLite store."""

    name: str
    tables: tuple[str, ...]
    version: Callable[[], int]
    open_store: Callable[[str], object]


def _graph_spec() -> StoreSpec:
    from graph.graph_store import SCHEMA_VERSION, GraphStore

    return StoreSpec("graph", ("nodes", "edges"), lambda: SCHEMA_VERSION, GraphStore)


def _symbol_cache_spec() -> StoreSpec:
    from indexing.symbol_cache import SCHEMA_VERSION, SymbolCache

    return StoreSpec("symbol_cache", ("symbols",), lambda: SCHEMA_VERSION, SymbolCache)


def _reference_graph_spec() -> StoreSpec:
    from indexing.reference_graph import SCHEMA_VERSION, ReferenceGraph

    return StoreSpec("reference_graph", ("occurrences",), lambda: SCHEMA_VERSION, ReferenceGraph)


def _cluster_store_spec() -> StoreSpec:
    from clustering.cluster_store import SCHEMA_VERSION, ClusterStore

    return StoreSpec(
        "cluster_store", ("clusters", "cluster_members"), lambda: SCHEMA_VERSION, ClusterStore
    )


_SPEC_LOADERS = (_graph_spec, _symbol_cache_spec, _reference_graph_spec, _cluster_store_spec)


def specs() -> list[StoreSpec]:
    return [load() for load in _SPEC_LOADERS]


def schema_versions() -> dict[str, int]:
    """Current schema version of every store — published in release metadata."""
    return {spec.name: spec.version() for spec in specs()}


@dataclass
class MigrationStep:
    path: Path
    store: str
    found_version: int
    expected_version: int
    action: str  # "none" | "rebuild" | "blocked"
    detail: str = ""

    @property
    def needed(self) -> bool:
        return self.action != "none"


def _tables_in(path: Path) -> set[str]:
    try:
        with sqlite3.connect(f"file:{path}?mode=ro", uri=True) as conn:
            rows = conn.execute("SELECT name FROM sqlite_master WHERE type='table'").fetchall()
            return {row[0] for row in rows}
    except sqlite3.Error:
        return set()


def _identify(path: Path, all_specs: list[StoreSpec]) -> Optional[StoreSpec]:
    tables = _tables_in(path)
    if not tables:
        return None
    for spec in all_specs:
        if set(spec.tables) <= tables:
            return spec
    return None


def plan(paths: Iterable[Path]) -> list[MigrationStep]:
    """Inspect SQLite files and report which caches a version change would rebuild."""
    all_specs = specs()
    steps: list[MigrationStep] = []

    for path in paths:
        path = Path(path)
        if not path.is_file():
            continue
        spec = _identify(path, all_specs)
        if spec is None:
            continue

        expected = spec.version()
        try:
            with sqlite3.connect(f"file:{path}?mode=ro", uri=True) as conn:
                found = read_schema_version(conn)
        except sqlite3.Error as exc:
            steps.append(MigrationStep(path, spec.name, -1, expected, "blocked", str(exc)))
            continue

        if found == expected:
            action, detail = "none", "up to date"
        elif found > expected:
            action, detail = (
                "blocked",
                "written by a newer CodeCortex — irreversible for this build",
            )
        else:
            action, detail = "rebuild", "stale cache, will be regenerated by re-indexing"
        steps.append(MigrationStep(path, spec.name, found, expected, action, detail))

    return steps


def discover(index_dir: Path) -> list[Path]:
    """SQLite files under an index directory (non-recursive plus one level down)."""
    index_dir = Path(index_dir)
    if not index_dir.is_dir():
        return []
    found = sorted(index_dir.glob("*.db")) + sorted(index_dir.glob("*/*.db"))
    return found


def run(paths: Iterable[Path], *, dry_run: bool = False) -> list[MigrationStep]:
    """Execute the plan. Rebuilds happen by reopening each store, which stamps
    and recreates the schema through `core.db_schema.ensure_schema`."""
    steps = plan(paths)
    if dry_run:
        return steps

    by_name = {spec.name: spec for spec in specs()}
    for step in steps:
        if step.action != "rebuild":
            continue
        spec = by_name[step.store]
        logger.info("Rebuilding %s cache at %s", step.store, step.path)
        store = spec.open_store(str(step.path))
        close = getattr(store, "close", None)
        if callable(close):
            close()
    return steps


def requires_migration(release_schema_versions: dict[str, int]) -> bool:
    """Whether a release's schema versions differ from this installation's."""
    local = schema_versions()
    return any(local.get(name, 0) != version for name, version in release_schema_versions.items())
